services:
  - type: web
    name: toolson
    runtime: python
    pythonVersion: 3.12.6
    workingDirectory: Toolson


    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput

    startCommand: gunicorn Toolson.wsgi:application --bind 0.0.0.0:$PORT